"""empty message

Revision ID: 3e2526af6cfc
Revises: 263260930929
Create Date: 2023-11-27 03:49:56.254940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2526af6cfc'
down_revision = '263260930929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon1', sa.String(), nullable=False),
    sa.Column('pokemon2', sa.String(), nullable=False),
    sa.Column('pokemon3', sa.String(), nullable=False),
    sa.Column('pokemon4', sa.String(), nullable=False),
    sa.Column('pokemon5', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon1'),
    sa.UniqueConstraint('pokemon2'),
    sa.UniqueConstraint('pokemon3'),
    sa.UniqueConstraint('pokemon4'),
    sa.UniqueConstraint('pokemon5')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_team')
    # ### end Alembic commands ###
